name: push-action
run-name: Push action

on:
  push:

jobs:
  run-in-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run in container
        uses: ./.github/container-action
        with:
          entrypoint: /github/workspace/test.sh
