name: push-action
run-name: Push action

on:
  push:
    branches:
      - main

jobs:
  run-in-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run in container
        uses: ./
        with:
          entrypoint: /github/workspace/test.sh
